[WIP] Fast irods querying
bihealth/cubi-tk pull request #184
Opened 2023-06-28 07:40 UTC by xiamaz

Still work in progress but already reduces irods pull commands to <30s. Querying all files from a single sodar assay takes ~2.5s. The slow part is reading each `md5` checksum.

# Todo

- [ ] clean up codebase
- [ ] make filtering step cleaner
- [ ] clean up checksum extraction

Since irods already offers native checksumming, its unclear whether the current md5 checksums are really necessary. This should be cleared up.

2023-06-28 07:44 UTC, xiamaz commented
# Limitations

- support for replicates has been removed for now, but that feature had not been used anywhere in `cubi-tk`
- some hard-coded filters have not been adapted yet

2023-06-28 14:18 UTC, Nicolai-vKuegelgen commented
Just pushed my most recent version of implementing the query in irods/check.get_data_objects (branch 155-cubi-tk-snappy-pull-raw-data-is-slow-for-large-studies).

As discussed, probably best if you can merge that in, since the only other necessary changes will be the ones to remove opening the md5 files to get the checksums (the returned objects have a checksum attribute).

I also think there is no reason to create and use the custom class `IrodsDataObject`'s or `IrodsRawDataObject`'s, since the iRODSDataObject returned by get_data_objects (both previously with walk and now with query) has all of their attribute and functions and I see no reason why downsizing them should result in a noticable speedup.

2023-06-28 16:11 UTC, xiamaz commented
@Nicolai-vKuegelgen I merged your PR and pull raw and processed data should work again.

2023-06-29 14:41 UTC, Nicolai-vKuegelgen requested changes
I don't see the reason to change the output type of the `get_data_objs`function from dictionary to list, since this is likely to break depedencies.

2023-06-29 14:41 UTC, Nicolai-vKuegelgen commented on cubi_tk/snappy/retrieve_irods_collection.py
> +@attr.s(frozen=True, auto_attribs=True)
This is not needed anymore is it?

2023-06-29 19:54 UTC, xiamaz commented on cubi_tk/irods/check.py
> +        data_objs = []
The checksums are not needed anymore. Given that the object types are now different, everything working with the objects will need to be adapted anyways and we can just do that now.

2023-06-30 08:35 UTC, xiamaz commented on cubi_tk/irods/check.py
> +        data_objs = []
Given https://github.com/bihealth/cubi-tk/issues/185, will revert this for compatibility until that question is resolved.

2023-06-30 15:01 UTC, xiamaz commented on cubi_tk/irods/check.py
> +        data_objs = []
This is now reverted, but adaptations were still necessary to most code parts interacting with data objects.

2023-07-03 14:52 UTC, Nicolai-vKuegelgen reviewed
I think this mostly looks good now - a few minor things I'm 100% about.

2023-07-03 14:52 UTC, Nicolai-vKuegelgen commented on cubi_tk/irods/check.py
> +        data_objs = dict(files=[], checksums=[])
this should be `data_objs = dict(files=[], checksums={})` (dict for checksums), no?

2023-07-03 14:52 UTC, Nicolai-vKuegelgen commented on cubi_tk/irods/check.py
> +        dsp_files = data_objs
Since we leave the output of `get_data_objs` as is, this should not need any chnages, right?

2023-07-03 14:52 UTC, Nicolai-vKuegelgen commented on cubi_tk/snappy/pull_data_common.py
> +        'P001-N1-DNA1-WES1.vcf.gz'); Value: iRODS data (``DataObject``).
I think the correct calls/type name here is `iRODSDataObject` (at least its imported under that name in check.py; inside irods it iirc called `data_object`)

2023-07-03 14:52 UTC, Nicolai-vKuegelgen commented on cubi_tk/snappy/pull_data_common.py
> +        :type irods_obj_list: List[DataObject]
I think the correct calls/type name here is `iRODSDataObject` (at least its imported under that name in check.py; inside irods it iirc called `data_object`)

2023-07-03 14:52 UTC, Nicolai-vKuegelgen commented on cubi_tk/snappy/pull_processed_data.py
> +        'P001-N1-DNA1-WES1'); Value: iRODS data (``DataObject``).
I think the correct calls/type name here is iRODSDataObject (at least its imported under that name in check.py; inside irods it iirc called data_object)

2023-07-03 14:52 UTC, Nicolai-vKuegelgen commented on cubi_tk/snappy/pull_raw_data.py
> +        'P001-N1-DNA1-WES1.vcf.gz'); Value: iRODS data (``DataObject``).
I think the correct calls/type name here is iRODSDataObject (at least its imported under that name in check.py; inside irods it iirc called data_object)

2023-07-03 14:52 UTC, Nicolai-vKuegelgen commented on cubi_tk/snappy/pull_raw_data.py
> +        string (e.g., 'P001'); Value: iRODS data (``DataObject``).
as before

2023-07-03 14:52 UTC, Nicolai-vKuegelgen commented on cubi_tk/snappy/pull_raw_data.py
> +        'P001_R1_001.fastq.gz'); Value: iRODS data (``DataObject``).
as before

2023-07-03 14:52 UTC, Nicolai-vKuegelgen commented on cubi_tk/snappy/pull_processed_data.py
> +            remote_files_dict=remote_file_objs,
mismatch between dict & obj (even if its just in the names)

2023-07-03 14:52 UTC, Nicolai-vKuegelgen commented on cubi_tk/snappy/retrieve_irods_collection.py
> +        Value: list of iRodsDataObject (attributes: 'file_name', 'irods_path', 'file_md5sum', 'replicas_md5sum').
this is should be the 'native' `iRODSDataObject` now, which has a full set of attributes

2023-07-03 14:52 UTC, Nicolai-vKuegelgen commented on cubi_tk/snappy/retrieve_irods_collection.py
> +        Value: list of iRodsDataObject (attributes: 'file_name', 'irods_path', 'file_md5sum', 'replicas_md5sum').
as above

2023-07-03 14:52 UTC, Nicolai-vKuegelgen commented on cubi_tk/sodar/check_remote.py
> +        :param remote_files_dict: Dictionary with remote filenames as keys and list of iRodsDataObject as values.
as above

2023-07-03 14:52 UTC, Nicolai-vKuegelgen commented on cubi_tk/sodar/check_remote.py
> +        :param remote_dict: Dictionary with remote filenames as keys and list of iRodsDataObject as values.
as above

2023-07-04 16:08 UTC, Nicolai-vKuegelgen approved these changes
LGTM

2023-07-04 18:37 UTC, merged