feat: presets for cubi-tk sodar ingest-fastq (#232 )
bihealth/cubi-tk pull request #235
Opened 2024-08-19 11:51 UTC by Nicolai-vKuegelgen

2024-08-19 13:14 UTC, Nicolai-vKuegelgen commented on cubi_tk/sodar/ingest_fastq.py
> +            "--preset. 'collection_name' is the target iRODS collection and will be filled with the (-m regex "
I'm adding an error if someone uses both  --src-regex and --remote-dir-pattern together with the non-default preset (afaik there is no good way to check if preset was manually defined same as the default value or not).

2024-09-02 09:06 UTC, tedil requested changes

2024-09-02 09:06 UTC, tedil commented on tests/test_sodar_ingest_fastq.py
> +        # dest_path,
Are there any tests left that cover this use-case? Otherwise, we should add one

2024-09-02 10:54 UTC, tedil approved these changes
LGTM

2024-09-02 11:13 UTC, merged